import { dataImgs } from "./src/assets";

export const dataPhimDeCu = [
  {
    title: "PHIM ĐỀ CỬ",
    film: [
      {
        idphim: "BoTuSieuDang",
        imgbig: dataImgs.imgBigBoTuSieuDang,
        img: dataImgs.imgBoTuSieuDang,
        quality: "Vietsub",
        title: "Bộ Tứ Siêu Đẳng",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "BuonThanBanThanh",
        imgbig: dataImgs.imgBigBuonThanBanThanh,
        img: dataImgs.imgBuonThanBanThanh,
        quality: "Vietsub",
        title: "Buôn Thần Bán Thánh",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "CuoiMaGiaiHan",
        imgbig: dataImgs.imgBigCuoiMaGiaiHan,
        img: dataImgs.imgCuoiMaGiaiHan,
        quality: "Vietsub",
        title: "Cưới Ma Giải Hạn",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "DiepQuyTanNuong",
        imgbig: dataImgs.imgBigDiepQuyTanNuong,
        img: dataImgs.imgDiepQuyTanNuong,
        quality: "Vietsub",
        title: "Điệp Quỷ Tân Nương",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "f1",
        imgbig: dataImgs.imgBigF1,
        img: dataImgs.imgF1,
        quality: "Vietsub",
        title: "F1",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GaTuThan",
        imgbig: dataImgs.imgBigGaTuThan,
        img: dataImgs.imgGaTuThan,
        quality: "Vietsub",
        title: "Gã Tử Thần",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GioThaMau",
        imgbig: dataImgs.imgBigGioThaMau,
        img: dataImgs.imgGioThaMau,
        quality: "Vietsub",
        title: "Giờ Thả Máu",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "PhongThan2",
        imgbig: dataImgs.imgBigPhongThan2,
        img: dataImgs.imgPhongThan2,
        quality: "Vietsub",
        title: "Phong Thần 2",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Smurts",
        imgbig: dataImgs.imgBigSmurts,
        img: dataImgs.imgSmurts,
        quality: "Vietsub",
        title: "Smurts",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Superman2025",
        imgbig: dataImgs.imgBigSuperman2025,
        img: dataImgs.imgSuperman2025,
        quality: "Vietsub",
        title: "Superman 2025",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TheGioiKhungLong",
        imgbig: dataImgs.imgBigTheGioiKhungLong,
        img: dataImgs.imgTheGioiKhungLong,
        quality: "Vietsub",
        title: "Thế Giới Khủng Long",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TiengOnQuyDi",
        imgbig: dataImgs.imgBigTiengOnQuyDi,
        img: dataImgs.imgTiengOnQuyDi,
        quality: "Vietsub",
        title: "Tiếng Ồn Quỷ Dị",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
    ],
  },
];

export const dataPhimLe = [
  {
    title: "PHIM LẺ MỚI",
    list: [
      {
        id: "hanhdong",
        title: "Hành động",
      },
      {
        id: "hoathinh",
        title: "Hoạt hình",
      },
      {
        id: "kinhdi",
        title: "Kinh dị",
      },
      {
        id: "haihuoc",
        title: "Hài hước",
      },
    ],
    film: [
      {
        idphim: "BoTuSieuDang",
        imgbig: dataImgs.imgBigBoTuSieuDang,
        img: dataImgs.imgBoTuSieuDang,
        quality: "Vietsub",
        title: "Bộ Tứ Siêu Đẳng",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "BuonThanBanThanh",
        imgbig: dataImgs.imgBigBuonThanBanThanh,
        img: dataImgs.imgBuonThanBanThanh,
        quality: "Vietsub",
        title: "Buôn Thần Bán Thánh",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "CuoiMaGiaiHan",
        imgbig: dataImgs.imgBigCuoiMaGiaiHan,
        img: dataImgs.imgCuoiMaGiaiHan,
        quality: "Vietsub",
        title: "Cưới Ma Giải Hạn",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "DiepQuyTanNuong",
        imgbig: dataImgs.imgBigDiepQuyTanNuong,
        img: dataImgs.imgDiepQuyTanNuong,
        quality: "Vietsub",
        title: "Điệp Quỷ Tân Nương",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "f1",
        imgbig: dataImgs.imgBigF1,
        img: dataImgs.imgF1,
        quality: "Vietsub",
        title: "F1",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GaTuThan",
        imgbig: dataImgs.imgBigGaTuThan,
        img: dataImgs.imgGaTuThan,
        quality: "Vietsub",
        title: "Gã Tử Thần",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GioThaMau",
        imgbig: dataImgs.imgBigGioThaMau,
        img: dataImgs.imgGioThaMau,
        quality: "Vietsub",
        title: "Giờ Thả Máu",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "PhongThan2",
        imgbig: dataImgs.imgBigPhongThan2,
        img: dataImgs.imgPhongThan2,
        quality: "Vietsub",
        title: "Phong Thần 2",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Smurts",
        imgbig: dataImgs.imgBigSmurts,
        img: dataImgs.imgSmurts,
        quality: "Vietsub",
        title: "Smurts",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Superman2025",
        imgbig: dataImgs.imgBigSuperman2025,
        img: dataImgs.imgSuperman2025,
        quality: "Vietsub",
        title: "Superman 2025",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TheGioiKhungLong",
        imgbig: dataImgs.imgBigTheGioiKhungLong,
        img: dataImgs.imgTheGioiKhungLong,
        quality: "Vietsub",
        title: "Thế Giới Khủng Long",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TiengOnQuyDi",
        imgbig: dataImgs.imgBigTiengOnQuyDi,
        img: dataImgs.imgTiengOnQuyDi,
        quality: "Vietsub",
        title: "Tiếng Ồn Quỷ Dị",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
    ],
  },
];

export const dataPhimBoMoi = [
  {
    title: "PHIM BỘ MỚI",
    list: [
      {
        id: 1,
        title: "Hàn Quốc",
      },
      {
        id: 1,
        title: "Trung Quốc",
      },
      {
        id: 1,
        title: "Âu - Mỹ",
      },
      {
        id: 1,
        title: "Phim Bộ Full",
      },
    ],
    film: [
      {
        idphim: "BoTuSieuDang",
        imgbig: dataImgs.imgBigBoTuSieuDang,
        img: dataImgs.imgBoTuSieuDang,
        quality: "Vietsub",
        title: "Bộ Tứ Siêu Đẳng",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "BuonThanBanThanh",
        imgbig: dataImgs.imgBigBuonThanBanThanh,
        img: dataImgs.imgBuonThanBanThanh,
        quality: "Vietsub",
        title: "Buôn Thần Bán Thánh",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "CuoiMaGiaiHan",
        imgbig: dataImgs.imgBigCuoiMaGiaiHan,
        img: dataImgs.imgCuoiMaGiaiHan,
        quality: "Vietsub",
        title: "Cưới Ma Giải Hạn",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "DiepQuyTanNuong",
        imgbig: dataImgs.imgBigDiepQuyTanNuong,
        img: dataImgs.imgDiepQuyTanNuong,
        quality: "Vietsub",
        title: "Điệp Quỷ Tân Nương",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "f1",
        imgbig: dataImgs.imgBigF1,
        img: dataImgs.imgF1,
        quality: "Vietsub",
        title: "F1",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GaTuThan",
        imgbig: dataImgs.imgBigGaTuThan,
        img: dataImgs.imgGaTuThan,
        quality: "Vietsub",
        title: "Gã Tử Thần",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GioThaMau",
        imgbig: dataImgs.imgBigGioThaMau,
        img: dataImgs.imgGioThaMau,
        quality: "Vietsub",
        title: "Giờ Thả Máu",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "PhongThan2",
        imgbig: dataImgs.imgBigPhongThan2,
        img: dataImgs.imgPhongThan2,
        quality: "Vietsub",
        title: "Phong Thần 2",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Smurts",
        imgbig: dataImgs.imgBigSmurts,
        img: dataImgs.imgSmurts,
        quality: "Vietsub",
        title: "Smurts",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Superman2025",
        imgbig: dataImgs.imgBigSuperman2025,
        img: dataImgs.imgSuperman2025,
        quality: "Vietsub",
        title: "Superman 2025",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TheGioiKhungLong",
        imgbig: dataImgs.imgBigTheGioiKhungLong,
        img: dataImgs.imgTheGioiKhungLong,
        quality: "Vietsub",
        title: "Thế Giới Khủng Long",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TiengOnQuyDi",
        imgbig: dataImgs.imgBigTiengOnQuyDi,
        img: dataImgs.imgTiengOnQuyDi,
        quality: "Vietsub",
        title: "Tiếng Ồn Quỷ Dị",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
    ],
  },
];

export const dataPhimChieuRap = [
  {
    title: "PHIM CHIẾU RẠP MỚI",
    list: [
      {
        id: 1,
        title: "2023",
      },
      {
        id: 1,
        title: "2022",
      },
      {
        id: 1,
        title: "2021",
      },
      {
        id: 1,
        title: "2020",
      },
    ],
    film: [
      {
        idphim: "BoTuSieuDang",
        imgbig: dataImgs.imgBigBoTuSieuDang,
        img: dataImgs.imgBoTuSieuDang,
        quality: "Vietsub",
        title: "Bộ Tứ Siêu Đẳng",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "BuonThanBanThanh",
        imgbig: dataImgs.imgBigBuonThanBanThanh,
        img: dataImgs.imgBuonThanBanThanh,
        quality: "Vietsub",
        title: "Buôn Thần Bán Thánh",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "CuoiMaGiaiHan",
        imgbig: dataImgs.imgBigCuoiMaGiaiHan,
        img: dataImgs.imgCuoiMaGiaiHan,
        quality: "Vietsub",
        title: "Cưới Ma Giải Hạn",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "DiepQuyTanNuong",
        imgbig: dataImgs.imgBigDiepQuyTanNuong,
        img: dataImgs.imgDiepQuyTanNuong,
        quality: "Vietsub",
        title: "Điệp Quỷ Tân Nương",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "f1",
        imgbig: dataImgs.imgBigF1,
        img: dataImgs.imgF1,
        quality: "Vietsub",
        title: "F1",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GaTuThan",
        imgbig: dataImgs.imgBigGaTuThan,
        img: dataImgs.imgGaTuThan,
        quality: "Vietsub",
        title: "Gã Tử Thần",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GioThaMau",
        imgbig: dataImgs.imgBigGioThaMau,
        img: dataImgs.imgGioThaMau,
        quality: "Vietsub",
        title: "Giờ Thả Máu",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "PhongThan2",
        imgbig: dataImgs.imgBigPhongThan2,
        img: dataImgs.imgPhongThan2,
        quality: "Vietsub",
        title: "Phong Thần 2",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Smurts",
        imgbig: dataImgs.imgBigSmurts,
        img: dataImgs.imgSmurts,
        quality: "Vietsub",
        title: "Smurts",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Superman2025",
        imgbig: dataImgs.imgBigSuperman2025,
        img: dataImgs.imgSuperman2025,
        quality: "Vietsub",
        title: "Superman 2025",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TheGioiKhungLong",
        imgbig: dataImgs.imgBigTheGioiKhungLong,
        img: dataImgs.imgTheGioiKhungLong,
        quality: "Vietsub",
        title: "Thế Giới Khủng Long",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TiengOnQuyDi",
        imgbig: dataImgs.imgBigTiengOnQuyDi,
        img: dataImgs.imgTiengOnQuyDi,
        quality: "Vietsub",
        title: "Tiếng Ồn Quỷ Dị",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
    ],
  },
];

export const dataPhimThinhHanh = [
  {
    title: "PHIM THỊNH HÀNH",
    list: [
      {
        id: 1,
        title: "Phim Lẻ Thịnh hành",
      },
      {
        id: 1,
        title: "Phim Bộ Thịnh hành",
      },
    ],
    film: [
      {
        idphim: "BoTuSieuDang",
        imgbig: dataImgs.imgBigBoTuSieuDang,
        img: dataImgs.imgBoTuSieuDang,
        quality: "Vietsub",
        title: "Bộ Tứ Siêu Đẳng",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "BuonThanBanThanh",
        imgbig: dataImgs.imgBigBuonThanBanThanh,
        img: dataImgs.imgBuonThanBanThanh,
        quality: "Vietsub",
        title: "Buôn Thần Bán Thánh",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "CuoiMaGiaiHan",
        imgbig: dataImgs.imgBigCuoiMaGiaiHan,
        img: dataImgs.imgCuoiMaGiaiHan,
        quality: "Vietsub",
        title: "Cưới Ma Giải Hạn",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "DiepQuyTanNuong",
        imgbig: dataImgs.imgBigDiepQuyTanNuong,
        img: dataImgs.imgDiepQuyTanNuong,
        quality: "Vietsub",
        title: "Điệp Quỷ Tân Nương",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "f1",
        imgbig: dataImgs.imgBigF1,
        img: dataImgs.imgF1,
        quality: "Vietsub",
        title: "F1",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GaTuThan",
        imgbig: dataImgs.imgBigGaTuThan,
        img: dataImgs.imgGaTuThan,
        quality: "Vietsub",
        title: "Gã Tử Thần",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GioThaMau",
        imgbig: dataImgs.imgBigGioThaMau,
        img: dataImgs.imgGioThaMau,
        quality: "Vietsub",
        title: "Giờ Thả Máu",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "PhongThan2",
        imgbig: dataImgs.imgBigPhongThan2,
        img: dataImgs.imgPhongThan2,
        quality: "Vietsub",
        title: "Phong Thần 2",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Smurts",
        imgbig: dataImgs.imgBigSmurts,
        img: dataImgs.imgSmurts,
        quality: "Vietsub",
        title: "Smurts",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Superman2025",
        imgbig: dataImgs.imgBigSuperman2025,
        img: dataImgs.imgSuperman2025,
        quality: "Vietsub",
        title: "Superman 2025",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TheGioiKhungLong",
        imgbig: dataImgs.imgBigTheGioiKhungLong,
        img: dataImgs.imgTheGioiKhungLong,
        quality: "Vietsub",
        title: "Thế Giới Khủng Long",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TiengOnQuyDi",
        imgbig: dataImgs.imgBigTiengOnQuyDi,
        img: dataImgs.imgTiengOnQuyDi,
        quality: "Vietsub",
        title: "Tiếng Ồn Quỷ Dị",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
    ],
  },
];

export const dataPhimMoiSapChieu = [
  {
    title: "PHIM MỚI SẮP CHIẾU",
    list: [
      {
        id: 1,
        title: "",
      },
      {
        id: 1,
        title: "",
      },
    ],
    film: [
      {
        idphim: "BoTuSieuDang",
        imgbig: dataImgs.imgBigBoTuSieuDang,
        img: dataImgs.imgBoTuSieuDang,
        quality: "Vietsub",
        title: "Bộ Tứ Siêu Đẳng",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "BuonThanBanThanh",
        imgbig: dataImgs.imgBigBuonThanBanThanh,
        img: dataImgs.imgBuonThanBanThanh,
        quality: "Vietsub",
        title: "Buôn Thần Bán Thánh",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "CuoiMaGiaiHan",
        imgbig: dataImgs.imgBigCuoiMaGiaiHan,
        img: dataImgs.imgCuoiMaGiaiHan,
        quality: "Vietsub",
        title: "Cưới Ma Giải Hạn",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "DiepQuyTanNuong",
        imgbig: dataImgs.imgBigDiepQuyTanNuong,
        img: dataImgs.imgDiepQuyTanNuong,
        quality: "Vietsub",
        title: "Điệp Quỷ Tân Nương",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "f1",
        imgbig: dataImgs.imgBigF1,
        img: dataImgs.imgF1,
        quality: "Vietsub",
        title: "F1",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GaTuThan",
        imgbig: dataImgs.imgBigGaTuThan,
        img: dataImgs.imgGaTuThan,
        quality: "Vietsub",
        title: "Gã Tử Thần",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GioThaMau",
        imgbig: dataImgs.imgBigGioThaMau,
        img: dataImgs.imgGioThaMau,
        quality: "Vietsub",
        title: "Giờ Thả Máu",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "PhongThan2",
        imgbig: dataImgs.imgBigPhongThan2,
        img: dataImgs.imgPhongThan2,
        quality: "Vietsub",
        title: "Phong Thần 2",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Smurts",
        imgbig: dataImgs.imgBigSmurts,
        img: dataImgs.imgSmurts,
        quality: "Vietsub",
        title: "Smurts",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Superman2025",
        imgbig: dataImgs.imgBigSuperman2025,
        img: dataImgs.imgSuperman2025,
        quality: "Vietsub",
        title: "Superman 2025",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TheGioiKhungLong",
        imgbig: dataImgs.imgBigTheGioiKhungLong,
        img: dataImgs.imgTheGioiKhungLong,
        quality: "Vietsub",
        title: "Thế Giới Khủng Long",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TiengOnQuyDi",
        imgbig: dataImgs.imgBigTiengOnQuyDi,
        img: dataImgs.imgTiengOnQuyDi,
        quality: "Vietsub",
        title: "Tiếng Ồn Quỷ Dị",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
    ],
  },
];

export const dataCoTheMuonXem = [
  {
    title: "CÓ THỂ BẠN CŨNG MUỐN XEM",
    list: [
      {
        id: 1,
        title: " ",
      },
      {
        id: 1,
        title: "",
      },
    ],
    film: [
      {
        idphim: "BoTuSieuDang",
        imgbig: dataImgs.imgBigBoTuSieuDang,
        img: dataImgs.imgBoTuSieuDang,
        quality: "Vietsub",
        title: "Bộ Tứ Siêu Đẳng",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "BuonThanBanThanh",
        imgbig: dataImgs.imgBigBuonThanBanThanh,
        img: dataImgs.imgBuonThanBanThanh,
        quality: "Vietsub",
        title: "Buôn Thần Bán Thánh",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "CuoiMaGiaiHan",
        imgbig: dataImgs.imgBigCuoiMaGiaiHan,
        img: dataImgs.imgCuoiMaGiaiHan,
        quality: "Vietsub",
        title: "Cưới Ma Giải Hạn",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "DiepQuyTanNuong",
        imgbig: dataImgs.imgBigDiepQuyTanNuong,
        img: dataImgs.imgDiepQuyTanNuong,
        quality: "Vietsub",
        title: "Điệp Quỷ Tân Nương",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "f1",
        imgbig: dataImgs.imgBigF1,
        img: dataImgs.imgF1,
        quality: "Vietsub",
        title: "F1",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GaTuThan",
        imgbig: dataImgs.imgBigGaTuThan,
        img: dataImgs.imgGaTuThan,
        quality: "Vietsub",
        title: "Gã Tử Thần",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "GioThaMau",
        imgbig: dataImgs.imgBigGioThaMau,
        img: dataImgs.imgGioThaMau,
        quality: "Vietsub",
        title: "Giờ Thả Máu",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "PhongThan2",
        imgbig: dataImgs.imgBigPhongThan2,
        img: dataImgs.imgPhongThan2,
        quality: "Vietsub",
        title: "Phong Thần 2",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Smurts",
        imgbig: dataImgs.imgBigSmurts,
        img: dataImgs.imgSmurts,
        quality: "Vietsub",
        title: "Smurts",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "Superman2025",
        imgbig: dataImgs.imgBigSuperman2025,
        img: dataImgs.imgSuperman2025,
        quality: "Vietsub",
        title: "Superman 2025",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TheGioiKhungLong",
        imgbig: dataImgs.imgBigTheGioiKhungLong,
        img: dataImgs.imgTheGioiKhungLong,
        quality: "Vietsub",
        title: "Thế Giới Khủng Long",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
      {
        idphim: "TiengOnQuyDi",
        imgbig: dataImgs.imgBigTiengOnQuyDi,
        img: dataImgs.imgTiengOnQuyDi,
        quality: "Vietsub",
        title: "Tiếng Ồn Quỷ Dị",
        category: "Phim Hành Động",
        scoreRot: "96%",
        year: "2025",
        director: "Joseph Kosinski",
        duration: "2 giờ",
        country: "Âu Mỹ",
        scoreIMDb: "9.6",
        charecter:
          "Brad Pitt, Damson Idris, Javier Bardem, Kerry Condon, Tobias Menzies",
        moviecontent:
          "F1 F1 the Movie 2025 Lấy bối cảnh khi Sonny Hayes (Brad Pitt) – từng được mệnh danh là “thiên tài chưa được vinh danh” của làng Formula 1 thập niên 1990 – buộc phải giải nghệ sau tai nạn khủng khiếp. Ba mươi năm sau, anh trở lại đường đua trong vai trò lái thuê và được người bạn cũ, Ruben Cervantes (Javier Bardem) – lúc này là ông chủ đội đua APXGP đang sa sút – thuyết phục chấp nhận cơ hội cuối cùng để cứu đội và cạnh tranh đỉnh cao thế giới. Sonny cùng tay đua trẻ Joshua Pearce (Damson Idris) sẽ đối đầu và học cách tin tưởng nhau để tìm đường trở lại vinh quang",
      },
    ],
  },
];
